//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class E {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal E() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Language.E", typeof(E).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF(After Meal).
        /// </summary>
        internal static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD(Twice).
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM(Before Meal).
        /// </summary>
        internal static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        internal static string BRUSH {
            get {
                return ResourceManager.GetString("BRUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT(Bed Time).
        /// </summary>
        internal static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Interval.
        /// </summary>
        internal static string DAYINTERVAL {
            get {
                return ResourceManager.GetString("DAYINTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drops.
        /// </summary>
        internal static string DROPS {
            get {
                return ResourceManager.GetString("DROPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Ear.
        /// </summary>
        internal static string EAR {
            get {
                return ResourceManager.GetString("EAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES (Early Morning).
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Eye.
        /// </summary>
        internal static string EYE {
            get {
                return ResourceManager.GetString("EYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Fridge.
        /// </summary>
        internal static string FRIDGE {
            get {
                return ResourceManager.GetString("FRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Gargil.
        /// </summary>
        internal static string GARGIL {
            get {
                return ResourceManager.GetString("GARGIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycerine.
        /// </summary>
        internal static string GLCERINE {
            get {
                return ResourceManager.GetString("GLCERINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Hair Roots.
        /// </summary>
        internal static string HAIR {
            get {
                return ResourceManager.GetString("HAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Hardly _ Mix.
        /// </summary>
        internal static string HARDMIX {
            get {
                return ResourceManager.GetString("HARDMIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Hardly _ Seperately.
        /// </summary>
        internal static string HARDSEPERATE {
            get {
                return ResourceManager.GetString("HARDSEPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey.
        /// </summary>
        internal static string HONEY {
            get {
                return ResourceManager.GetString("HONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string HOURLY {
            get {
                return ResourceManager.GetString("HOURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HW.
        /// </summary>
        internal static string HW {
            get {
                return ResourceManager.GetString("HW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khurag.
        /// </summary>
        internal static string KHURAG {
            get {
                return ResourceManager.GetString("KHURAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        internal static string MILK {
            get {
                return ResourceManager.GetString("MILK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply_Mix.
        /// </summary>
        internal static string MIX {
            get {
                return ResourceManager.GetString("MIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNEN(All 3 Times).
        /// </summary>
        internal static string MNEN {
            get {
                return ResourceManager.GetString("MNEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Mouth Ulcers.
        /// </summary>
        internal static string MOUTH {
            get {
                return ResourceManager.GetString("MOUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Nose.
        /// </summary>
        internal static string NOSE {
            get {
                return ResourceManager.GetString("NOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string NOW {
            get {
                return ResourceManager.GetString("NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD(OneTime).
        /// </summary>
        internal static string OD {
            get {
                return ResourceManager.GetString("OD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply_Seperately.
        /// </summary>
        internal static string SEPERATE {
            get {
                return ResourceManager.GetString("SEPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoS.
        /// </summary>
        internal static string SoS {
            get {
                return ResourceManager.GetString("SoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab..
        /// </summary>
        internal static string TAB {
            get {
                return ResourceManager.GetString("TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDS (Thrice).
        /// </summary>
        internal static string TDS {
            get {
                return ResourceManager.GetString("TDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSF.
        /// </summary>
        internal static string TSF {
            get {
                return ResourceManager.GetString("TSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string WATER {
            get {
                return ResourceManager.GetString("WATER", resourceCulture);
            }
        }
    }
}
