//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class H {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal H() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS.Language.H", typeof(H).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खाने के बाद.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दो बार.
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खाने से पहले.
        /// </summary>
        internal static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्रश से.
        /// </summary>
        internal static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सोने से पहले.
        /// </summary>
        internal static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दिन के अंतराल मे.
        /// </summary>
        internal static string DAYINTERVAL {
            get {
                return ResourceManager.GetString("DAYINTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बूँद.
        /// </summary>
        internal static string Drops {
            get {
                return ResourceManager.GetString("Drops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कान मे डालना हैं.
        /// </summary>
        internal static string EAR {
            get {
                return ResourceManager.GetString("EAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सुबह.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हर.
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आँख मे डालना हैं.
        /// </summary>
        internal static string EYE {
            get {
                return ResourceManager.GetString("EYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एवं दवा फ्रिज मे रखे.
        /// </summary>
        internal static string FRIDGE {
            get {
                return ResourceManager.GetString("FRIDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गर गारा करे.
        /// </summary>
        internal static string GARGIL {
            get {
                return ResourceManager.GetString("GARGIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्लीसरिन के संग.
        /// </summary>
        internal static string Glycerine {
            get {
                return ResourceManager.GetString("Glycerine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बालों की जड़ों में.
        /// </summary>
        internal static string HAIR {
            get {
                return ResourceManager.GetString("HAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मले मिला के.
        /// </summary>
        internal static string HARDMIX {
            get {
                return ResourceManager.GetString("HARDMIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मले अलग अलग.
        /// </summary>
        internal static string HARDSEPERATE {
            get {
                return ResourceManager.GetString("HARDSEPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शहद के संग.
        /// </summary>
        internal static string Honey {
            get {
                return ResourceManager.GetString("Honey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घंटे पर.
        /// </summary>
        internal static string HOURLY {
            get {
                return ResourceManager.GetString("HOURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घंटे.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गरम  पानी के संग.
        /// </summary>
        internal static string HW {
            get {
                return ResourceManager.GetString("HW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खुराक.
        /// </summary>
        internal static string Khurag {
            get {
                return ResourceManager.GetString("Khurag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दूध के संग.
        /// </summary>
        internal static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनट.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनट पर.
        /// </summary>
        internal static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगाए मिलाके.
        /// </summary>
        internal static string MIX {
            get {
                return ResourceManager.GetString("MIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सुबह , दो पहर , शाम, रात.
        /// </summary>
        internal static string MNEN {
            get {
                return ResourceManager.GetString("MNEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुँह के छालों मे.
        /// </summary>
        internal static string MOUTH {
            get {
                return ResourceManager.GetString("MOUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दोनों नाक मे डालना हैं.
        /// </summary>
        internal static string NOSE {
            get {
                return ResourceManager.GetString("NOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभी.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एक बार.
        /// </summary>
        internal static string OD {
            get {
                return ResourceManager.GetString("OD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 बूंद - सुबह.
        /// </summary>
        internal static string POSOLOGYCHECK {
            get {
                return ResourceManager.GetString("POSOLOGYCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगाए अलग .. अलग.
        /// </summary>
        internal static string SEPERATE {
            get {
                return ResourceManager.GetString("SEPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परेशानी बढ़ने पर.
        /// </summary>
        internal static string SoS {
            get {
                return ResourceManager.GetString("SoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गोली.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तीन बार.
        /// </summary>
        internal static string TDS {
            get {
                return ResourceManager.GetString("TDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चम्मच.
        /// </summary>
        internal static string TSF {
            get {
                return ResourceManager.GetString("TSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पानी के संग.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
    }
}
